export default[
    {
      key:'1',
      title:"首页",
      icon:'home',
      path:'/admin/home'
    },
    {
     key:'2',
     title:'用户管理',
     icon:'user',
     path:'/admin/user',
    },
    {
      key:'8',
      title:"商品管理",
      icon:'set',
      path:'/admin/commodity',
      children:[
        {
          key:'8-1',
          title:'商品信息',
          path:'/admin/commoditylist',
        },
        {
          key:'8-2',
          title:'商品添加',
          path:'/admin/commodityadd'
        }
      ]
    },
    {
      key:'10',
      title:"数据管理",
      icon:'set',
      children:[
        {
          key:'10-1',
          title:'树状图',
          path:'/admin/bar',
        },
        {
          key:'8-2',
          title:'饼状图',
          path:'/admin/line'
        }
      ]
    },
    {
      key:'9',
      title:"设置",
      icon:'set',
      path:'/admin/set'
    },
  ]